# Generated by Django 4.0.5 on 2022-07-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna_nombre', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=30)),
                ('tipo_vacuna', models.CharField(max_length=30)),
                ('lote', models.CharField(max_length=30)),
                ('forma_administracion', models.CharField(max_length=30)),
            ],
        ),
    ]
